title: "Yash Parmar's GitHub Metrics"
config:
  timezone: "America/New_York"

metrics:
  - type: "row"
    metrics:
      - type: "contributions"
      - type: "languages"

  - type: "row"
    metrics:
      - type: "streak"
      - type: "isocalendar"
        duration: "full-year"

  - type: "row"
    metrics:
      - type: "leetcode"
        username: "yparmar"
        display_name: "LeetCode"
        show_ranking: true
